### ISSUE TITLE
Are there others alternatives to the OpenTok API?

### ISSUE THREAD

**Issue by jzvi12** [opentok/interactive-broadcast-js#46]
Is it possible to use a custom/private or other "free" API subscription instead of OpenTok API?

**Comment by rhainer** [comment]
Are you looking for more of a SaaS solution? If so, take a look at https://www.crowdcast.io/

**Comment by jzvi12** [comment]
> Are you looking for more of a SaaS solution? If so, take a look at https://www.crowdcast.io/

Thanks! I checked their RTMP service but I already owned a hosted RTMP (Nginx) server that simulcast to various platforms (Youtube, Facebook, etc)...

I would like to deploy an open source solution like IB with its conference functionality and send it as a live stream to my RTMP server.
